import type { Config } from "tailwindcss";

const config: Config = {
    darkMode: ["class"],
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "surface-container-highest": "#e0e3e5",
                "surface-variant": "#e0e3e5",
                "surface-tint": "#2b6954",
                "primary-fixed-dim": "#95d3ba",
                "surface-dim": "#d8dadc",
                "primary": "#003527",
                "on-error-container": "#93000a",
                "secondary": "#006a61",
                "on-primary": "#ffffff",
                "primary-fixed": "#b0f0d6",
                "on-tertiary-fixed-variant": "#294e3f",
                "inverse-primary": "#95d3ba",
                "primary-container": "#064e3b",
                "on-tertiary-container": "#93baa7",
                "outline-variant": "#bfc9c3",
                "tertiary": "#0e3427",
                "on-primary-fixed-variant": "#0b513d",
                "outline": "#707974",
                "error-container": "#ffdad6",
                "error": "#ba1a1a",
                "on-error": "#ffffff",
                "secondary-fixed-dim": "#6bd8cb",
                "on-secondary-container": "#006f66",
                "on-secondary-fixed": "#00201d",
                "surface-container-high": "#e6e8ea",
                "on-primary-container": "#80bea6",
                "tertiary-container": "#274b3c",
                "on-primary-fixed": "#002117",
                "tertiary-fixed-dim": "#a8cfbc",
                "on-tertiary": "#ffffff",
                "background": "#f7f9fb",
                "on-background": "#191c1e",
                "inverse-on-surface": "#eff1f3",
                "tertiary-fixed": "#c3ecd7",
                "surface-container": "#eceef0",
                "on-secondary": "#ffffff",
                "surface": "#f7f9fb",
                "surface-bright": "#f7f9fb",
                "secondary-container": "#86f2e4",
                "secondary-fixed": "#89f5e7",
                "on-surface": "#191c1e",
                "on-secondary-fixed-variant": "#005049",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f2f4f6",
                "on-tertiary-fixed": "#002115",
                "on-surface-variant": "#404944",
                "inverse-surface": "#2d3133",
            },
            fontFamily: {
                "display": ["var(--font-inter)"],
                "h2": ["var(--font-inter)"],
                "label-sm": ["var(--font-inter)"],
                "mono-data": ["var(--font-space-grotesk)"],
                "body-lg": ["var(--font-inter)"],
                "body-md": ["var(--font-inter)"],
                "h1": ["var(--font-inter)"]
            },
            fontSize: {
                "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "h2": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "label-sm": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500" }],
                "mono-data": ["14px", { "lineHeight": "1.2", "fontWeight": "500" }],
                "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "h1": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.015em", "fontWeight": "600" }]
            }
        },
    },
    plugins: [require("tailwindcss-animate")],
};
export default config;
